name: 'CI New Feature Tests'

on:
  workflow_dispatch:
  push:
    branches:
    - 'feature/*'

jobs:

##########################################################
########## TESTS for IN-DEVELOPMENT FEATURES #############
##########################################################

  github_dynamic_secrets_prefixed:
    runs-on: ubuntu-latest
    name: GitHub dynamic secrets (parsed with prefix)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch GitHub dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/github-secrets":"GH"}' #applies "GH_" prefix to dynamically parsed output names
        parse-dynamic-secrets: true

    - name: Verify Job Outputs (to known field names, pre-parsed with prefix)
      run: |
        echo "ID: ${{ steps.fetch-secrets.outputs.GH_id }}" 
        echo "TOKEN: ${{ steps.fetch-secrets.outputs.GH_token }}" 
        echo "TTL_IN_MINUTES: ${{ steps.fetch-secrets.outputs.GH_ttl_in_minutes }}" 

    - name: Verify Environment Variables (to known field names, pre-parsed with prefix)
      run: |
        echo "ID: ${{ env.GH_id }}"
        echo "TOKEN: ${{ env.GH_token }}"
        echo "TTL_IN_MINUTES: ${{ env.GH_ttl_in_minutes }}"
